name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    #TODO: Da decommentare quando sistemo la pipeline ci/cd.
    #- name: Build Docker Image
    #  run: docker build -t homeassistant:latest .