name: Lint Code and Configurations

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install Linters
      run: |
        pip install yamllint
        sudo apt-get update
        sudo apt-get install -y markdownlint-cli

    - name: Lint YAML files
      run: yamllint .

    - name: Lint Markdown Files
      run: markdownlint **/*.md